INFO - 2022-07-17 11:24:31,011 - Module:poolbot - Function:send_welcome Line:28 - Message:"tg_id OK"
ERROR - 2022-07-17 11:24:31,937 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,942 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,942 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,942 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,943 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,943 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,943 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,943 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,944 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,944 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,945 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,945 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,945 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,945 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,946 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,946 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,946 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,946 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,946 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,947 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,947 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,947 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,947 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,948 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,948 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,948 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,948 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,948 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,948 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,949 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,949 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,949 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:31,949 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
INFO - 2022-07-17 11:24:31,950 - Module:poolbot - Function:send_welcome Line:78 - Message:"parsing hh OK"
ERROR - 2022-07-17 11:24:32,440 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:32,441 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:32,441 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:32,441 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:24:32,442 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
INFO - 2022-07-17 11:24:32,442 - Module:poolbot - Function:send_welcome Line:97 - Message:"parsing sj OK"
INFO - 2022-07-17 11:34:06,725 - Module:poolbot - Function:send_welcome Line:28 - Message:"tg_id OK"
INFO - 2022-07-17 11:34:28,200 - Module:poolbot - Function:send_welcome Line:28 - Message:"tg_id OK"
INFO - 2022-07-17 11:36:54,584 - Module:poolbot - Function:send_welcome Line:28 - Message:"tg_id OK"
ERROR - 2022-07-17 11:36:55,102 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,105 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,106 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,106 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,106 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,107 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,107 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,107 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,108 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,108 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,108 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,108 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,109 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,109 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,109 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,110 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
INFO - 2022-07-17 11:36:55,110 - Module:poolbot - Function:send_welcome Line:78 - Message:"parsing hh OK"
ERROR - 2022-07-17 11:36:55,477 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:36:55,478 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
INFO - 2022-07-17 11:36:55,479 - Module:poolbot - Function:send_welcome Line:97 - Message:"parsing sj OK"
INFO - 2022-07-17 11:45:37,690 - Module:poolbot - Function:send_welcome Line:28 - Message:"tg_id OK"
ERROR - 2022-07-17 11:45:38,277 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,283 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,284 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,284 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,284 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,284 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,285 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,285 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,285 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,285 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,285 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,286 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,286 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,286 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,286 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,286 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,287 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,287 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,287 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,287 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,287 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,288 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,288 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,288 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,288 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,288 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,289 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,289 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,289 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,289 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,289 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,289 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,290 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
INFO - 2022-07-17 11:45:38,290 - Module:poolbot - Function:send_welcome Line:78 - Message:"parsing hh OK"
ERROR - 2022-07-17 11:45:38,825 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,826 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,827 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,827 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,827 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,828 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,828 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:45:38,828 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
INFO - 2022-07-17 11:45:38,828 - Module:poolbot - Function:send_welcome Line:97 - Message:"parsing sj OK"
INFO - 2022-07-17 11:47:42,307 - Module:poolbot - Function:send_welcome Line:28 - Message:"tg_id OK"
ERROR - 2022-07-17 11:47:42,901 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,905 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,906 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,906 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,906 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,907 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,907 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,907 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,907 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,908 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,908 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,908 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,908 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,909 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,909 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,909 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,910 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,910 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,910 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,911 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,911 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,911 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,911 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,912 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,912 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,912 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,912 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,913 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,913 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,913 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,913 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,913 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:42,914 - Module:manual_parse_hh - Function:go_parse_hh Line:108 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_hh.py", line 97, in go_parse_hh
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
INFO - 2022-07-17 11:47:42,915 - Module:poolbot - Function:send_welcome Line:78 - Message:"parsing hh OK"
ERROR - 2022-07-17 11:47:43,396 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:43,396 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:43,397 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:43,397 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:43,397 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:43,397 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:43,397 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
ERROR - 2022-07-17 11:47:43,398 - Module:manual_parse_sj - Function:go_parse_sj Line:77 - Message:"Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance."
Traceback (most recent call last):
  File "/Users/ruslan/Desktop/dir/job_filter_app/parsers_and_bot/management/commands/manual_parse_sj.py", line 66, in go_parse_sj
    Vacancy.objects.create(
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "/Users/ruslan/Desktop/dir/job_filter_app/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "'ruslan'": "Vacancy.for_user" must be a "Global_Users" instance.
INFO - 2022-07-17 11:47:43,398 - Module:poolbot - Function:send_welcome Line:97 - Message:"parsing sj OK"
